import { pgTable, uuid, varchar, text, integer, decimal, date, timestamp } from 'drizzle-orm/pg-core'

export const alejandriLibros = pgTable('alejandria_libros', {
  id: uuid('id').defaultRandom().primaryKey(),
  usuarioId: uuid('usuario_id').notNull(),
  titulo: varchar('titulo', { length: 255 }).notNull(),
  autor: varchar('autor', { length: 255 }),
  genero: varchar('genero', { length: 50 }),
  estado: varchar('estado', { length: 20 }).default('pendiente').notNull(),
  paginasTotales: integer('paginas_totales'),
  paginasLeidas: integer('paginas_leidas').default(0),
  fechaInicio: date('fecha_inicio'),
  fechaFin: date('fecha_fin'),
  coverUrl: text('cover_url'),
  criterioEscritura: integer('criterio_escritura'),
  criterioTrama: integer('criterio_trama'),
  criterioPersonajes: integer('criterio_personajes'),
  criterioRitmo: integer('criterio_ritmo'),
  criterioImpactoPersonal: integer('criterio_impacto_personal'),
  calificacionFinal: decimal('calificacion_final', { precision: 4, scale: 2 }),
  resena: text('resena'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
})

export const michelinRecetas = pgTable('michelin_recetas', {
  id: uuid('id').defaultRandom().primaryKey(),
  usuarioId: uuid('usuario_id').notNull(),
  nombre: varchar('nombre', { length: 255 }).notNull(),
  tipo: varchar('tipo', { length: 20 }),
  origen: varchar('origen', { length: 100 }),
  dificultad: integer('dificultad'),
  tiempoMinutos: integer('tiempo_minutos'),
  ingredientes: text('ingredientes').array(),
  instrucciones: text('instrucciones'),
  estado: varchar('estado', { length: 20 }).default('pendiente').notNull(),
  vecesCocinada: integer('veces_cocinada').default(0),
  urlReferencia: text('url_referencia'),
  fotoUrl: text('foto_url'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
})

export const odysseiaDestinos = pgTable('odysseia_destinos', {
  id: uuid('id').defaultRandom().primaryKey(),
  usuarioId: uuid('usuario_id').notNull(),
  nombre: varchar('nombre', { length: 255 }).notNull(),
  pais: varchar('pais', { length: 100 }),
  categorias: text('categorias').array(),
  estado: varchar('estado', { length: 20 }).default('pendiente').notNull(),
  fechaVisita: date('fecha_visita'),
  duracionDias: integer('duracion_dias'),
  fotosUrls: text('fotos_urls').array(),
  calificacion: integer('calificacion'),
  costoEstimado: decimal('costo_estimado', { precision: 15, scale: 2 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
})

export const nemesisJuegos = pgTable('nemesis_juegos', {
  id: uuid('id').defaultRandom().primaryKey(),
  usuarioId: uuid('usuario_id').notNull(),
  nombre: varchar('nombre', { length: 255 }).notNull(),
  plataforma: varchar('plataforma', { length: 20 }),
  genero: varchar('genero', { length: 100 }),
  estado: varchar('estado', { length: 20 }).default('por_jugar').notNull(),
  fechaInicio: date('fecha_inicio'),
  fechaCompletado: date('fecha_completado'),
  horasJugadas: decimal('horas_jugadas', { precision: 6, scale: 1 }),
  precio: decimal('precio', { precision: 10, scale: 2 }),
  coverUrl: text('cover_url'),
  criterioHistoria: integer('criterio_historia'),
  criterioJugabilidad: integer('criterio_jugabilidad'),
  criterioGraficos: integer('criterio_graficos'),
  criterioMusica: integer('criterio_musica'),
  criterioRejugabilidad: integer('criterio_rejugabilidad'),
  criterioDificultad: integer('criterio_dificultad'),
  calificacionFinal: decimal('calificacion_final', { precision: 4, scale: 2 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
})
